site_name: vericlient
site_url: https://clarriu97.github.io/vericlient/
repo_url: https://github.com/clarriu97/vericlient
repo_name: clarriu97/vericlient
nav:
  - Get started: index.md
  - Supported endpoints: supported_endpoints.md
  - Configuration: api_docs/vericlient.md
  - Error handling: errors.md
  - Usage:
    - das-Peak: api_docs/daspeak/client_usage.md
    - VCSP: api_docs/vcsp/client_usage.md
  - API reference:
    - das-Peak: api_docs/daspeak/client.md
    - VCSP: api_docs/vcsp/client.md
  - Changelog: CHANGELOG.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - tables
  - codehilite
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css


theme:
  name: material
  language: en
  palette:
    # Follow the reader's system setting, and let them override it.
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.footer
    - content.code.copy
    - navigation.tabs
    - search.highlight
    - search.share
    - toc.follow
    - content.code.annotate
    - content.tabs.link
    - content.tabs.expand
    - header.autohide
