site_name: vericlient
site_url: https://clarriu97.github.io/vericlient/
repo_url: https://github.com/clarriu97/vericlient
repo_name: clarriu97/vericlient
nav:
  - Get Started: index.md
  - Changelog: CHANGELOG.md
  - API Documentation:
      - Vericlient: api_docs/vericlient.md
      - Daspeak client: api_docs/daspeak/client.md
      - Daspeak models: api_docs/daspeak/models.md
      - Daspeak exceptions: api_docs/daspeak/exceptions.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: pink
    accent: pink
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - search.highlight
    - search.share
    - toc.follow
    - content.code.annotate
    - content.tabs.link
    - content.tabs.expand
    - header.autohide
