"""Module to define the models for the VCSP API."""

# ruff: noqa: N805, D102, ANN201
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, field_validator

from vericlient.types import Media


class VcspResponse(BaseModel):
    """Base class for the VCSP API responses.

    Carries no fields of its own: it exists so every VCSP response shares a type, and so
    anything the API starts returning across the board has somewhere to go.
    """


class CredentialConfigurationsOutput(VcspResponse):
    """Output class for the credential configurations endpoint.

    Attributes:
        credential_configurations: The credential configurations

    """

    credential_configurations: list[str]


class AssuranceMethodsOutput(VcspResponse):
    """Output class for the assurance methods endpoint.

    Attributes:
        assurance_methods: The assurance methods

    """

    assurance_methods: list[str]


class AssuranceMethodSchema(BaseModel):
    """Schema class for the assurance method.

    Attributes:
        json_schema: The JSON schema of the assurance method, serialised as `$schema`
        title: The title of the assurance method
        type: The type of the assurance method
        properties: The properties of the assurance method
        required: The required properties of the assurance method
        additionalProperties: Whether additional properties are allowed

    """

    model_config = ConfigDict(populate_by_name=True)

    json_schema: str = Field(alias="$schema")
    title: str
    type: str
    properties: dict
    required: list[str] | None = None
    additionalProperties: bool  # noqa: N815


class AssuranceMethodInput(BaseModel):
    """Input class for the assurance method endpoint.

    Attributes:
        urn: The urn of the assurance method

    """

    model_config = ConfigDict(title="get_assurance_method_info()")

    urn: str


class AssuranceMethodOutput(VcspResponse):
    """Output class for the assurance method endpoint.

    Attributes:
        urn: The urn of the assurance method
        json_schema: The schema of the assurance method, serialised as `schema`

    """

    model_config = ConfigDict(populate_by_name=True)

    urn: str
    json_schema: AssuranceMethodSchema = Field(alias="schema")


class Sample(BaseModel):
    """Base class for the Sample.

    Attributes:
        valid_from: The date from which the sample is valid
        valid_until: The date until which the sample is valid
        type: The type of the sample, e.g. "voice", "face"
        content_type: The content type of the sample, e.g. "audio/wav", "image/jpeg"
        analysis: The analysis of the sample

    """

    valid_from: str
    valid_until: str
    type: str
    content_type: str
    analysis: dict


class Applicant(BaseModel):
    """Base class for the Applicant.

    Attributes:
        subject_id: The subject_id of the applicant (optional). If not provided, it will
            be generated by the system and returned in the response
        credential_configuration_urn: The credential configuration urn
        tags: The tags of the applicant
        claims: The claims of the applicant
        assurance_method_urn: The assurance method urn
        assurance: The assurance of the applicant

    """

    subject_id: str | None = None
    credential_configuration_urn: str
    tags: list[str] | None = []
    claims: dict | None = {}
    assurance_method_urn: str
    assurance: dict


class EnrollmentInput(BaseModel):
    """Input class for the enrollment endpoint.

    Attributes:
        sample: The sample to generate the credential with.
            It can be a path to a file or a bytes object
            with the audio content
        applicant: The applicant to enroll
        content_type: The media type to declare for the sample, such as `audio/wav` or
            `image/jpeg`. Optional: it is inferred from the file extension for a path and
            from the magic bytes for a bytes object. Set it when the guess would be wrong,
            since VCSP answers with a 500 if the declared type does not match the content

    """

    sample: Media
    applicant: Applicant
    content_type: str | None = None

    @field_validator("sample")
    def must_be_str_or_bytes(cls, value: object):
        if not isinstance(value, (str, bytes)):
            error = "sample must be a string or a bytes object"
            raise TypeError(error)
        return value

    model_config = ConfigDict(arbitrary_types_allowed=True, title="enroll_subject()")


class EnrollmentOutput(BaseModel):
    """Output class for the enrollment endpoint.

    Attributes:
        credential_id: The credential_id of the applicant
        subject_id: The subject_id of the applicant

    """

    credential_id: str
    subject_id: str


class SubjectInput(BaseModel):
    """Input class to define a subject.

    Attributes:
        subject_id: The subject_id of the applicant

    """

    subject_id: str


class CredentialInput(BaseModel):
    """Input class to define a credential.

    Attributes:
        credential_id: The credential_id of the applicant

    """

    credential_id: str


class DeleteSubjectInput(SubjectInput):
    """Input class for the delete account endpoint.

    Attributes:
        subject_id: The account_id to delete

    """

    model_config = ConfigDict(title="delete_account()")


class DeleteCredentialInput(SubjectInput, CredentialInput):
    """Input class for the delete credential endpoint.

    Attributes:
        credential_id: The credential_id to delete
        subject_id: The subject from which the credential will be deleted

    """

    model_config = ConfigDict(title="delete_credential()")


class GetAccountInput(SubjectInput):
    """Input class for the get account endpoint.

    Attributes:
        subject_id: The account_id to get

    """

    model_config = ConfigDict(title="get_account()")


class GetCredentialInput(SubjectInput, CredentialInput):
    """Input class for the get a specific credential endpoint.

    Attributes:
        subject_id: The subject_id to get the credential from
        credential_id: The credential_id to get

    """

    model_config = ConfigDict(title="get_credential()")


class GetCredentialOutput(BaseModel):
    """Output class for the get credential endpoint.

    Attributes:
        sample: The sample of the applicant
        groups: The groups of the applicant
        issuer: The issuer
        id: The id of the applicant
        updated_at: The updated_at date
        created_at: The created_at date
        valid_from: The valid_from date
        valid_until: The valid_until date
        credential_configuration_urn: The credential_configuration_urn
        tags: The tags of the applicant
        claims: The claims of the applicant

    """

    sample: Sample
    groups: list[str]
    issuer: str
    id: str
    updated_at: str
    created_at: str
    valid_from: str
    valid_until: str
    credential_configuration_urn: str
    tags: list[str]
    claims: dict


class GetAccountOutput(VcspResponse):
    """Output class for the get account endpoint.

    Attributes:
        credentials: The credentials of the applicant
        updated_at: The updated_at date
        created_at: The created_at date
        subject_id: The subject_id of the applicant

    """

    credentials: list[str]
    updated_at: str
    created_at: str
    subject_id: str


class DeleteAccountInput(SubjectInput):
    """Input class for the delete account endpoint.

    Attributes:
        subject_id: The account_id to delete

    """


class GetCredentialsInput(SubjectInput):
    """Input class for the get all credentials from a subject endpoint.

    Attributes:
        subject_id: The account_id to get the credentials from

    """

    model_config = ConfigDict(title="get_all_subject_credentials()")


class GetCredentialsOutput(VcspResponse):
    """Output class for the get all credentials from a subject endpoint.

    Attributes:
        credentials: The credentials of the applicant

    """

    credentials: list[GetCredentialOutput]


class TagInput(BaseModel):
    """Input class for the tag endpoint.

    Attributes:
        name: The name of the tag

    """

    name: str


class TagOutput(TagInput):
    """Output class for the tag endpoint.

    Attributes:
        name: The name of the tag
        created_at: The created_at date

    """

    created_at: str


class CreateTagsInput(BaseModel):
    """Input class for the create tag endpoint.

    Attributes:
        tags: The tags to create

    """

    model_config = ConfigDict(title="create_tags()")

    tags: list[str]


class CreateTagsOutput(VcspResponse):
    """Output class for the create tag endpoint.

    Attributes:
        tags: The tags created
        created_at: The created_at date

    """

    tags: list[str]
    created_at: str


class GetTagsOutput(VcspResponse):
    """Output class for the get tags endpoint.

    Attributes:
        items: The tags
        total: The total number of tags
        page: The page number
        size: The size of the tags
        pages: The total number of pages

    """

    items: list[TagOutput]
    total: int
    page: int
    size: int
    pages: int


class DeleteTagInput(TagInput):
    """Input class for the delete tag endpoint.

    Attributes:
        name: The name of the tag

    """

    model_config = ConfigDict(title="delete_tag()")


class GroupInput(BaseModel):
    """Input class for the group endpoint.

    Attributes:
        name: The name of the group

    """

    name: str


class CreateGroupInput(GroupInput):
    """Input class for the create group endpoint.

    Attributes:
        name: The name of the group. Must match `^[a-zA-Z_][a-zA-Z0-9_]{2,63}$`, so letters,
            digits and underscores only, starting with a letter or an underscore
        credential_configuration_urn: The credential configuration the group holds
        description: A free-text description. Defaults to empty on the service
        expired_at: How long credentials are retained in the group, as an **ISO 8601
            duration** such as `P1Y` or `P30D` — not a date. The service answers with the
            resulting timestamp. Defaults to five years

    """

    model_config = ConfigDict(title="create_group()")

    credential_configuration_urn: str
    description: str | None = None
    expired_at: str | None = None


class CreateGroupOutput(VcspResponse):
    """Output class for the create group endpoint.

    Attributes:
        size: The number of credentials in the group
        created_at: The created_at date
        updated_at: The updated_at date
        credential_configuration_urn: The credential configuration the group holds
        name: The name of the group
        description: The description of the group
        expired_at: The date the credentials expire. Note the asymmetry with the input,
            which takes a duration rather than a date

    """

    size: int
    created_at: str
    updated_at: str
    credential_configuration_urn: str
    name: str
    description: str
    expired_at: str


class GetGroupsInput(BaseModel):
    """Input class for the get groups endpoint.

    Attributes:
        size: The size of the groups (optional), default is 100
        page: The page number (optional), default is 1

    """

    model_config = ConfigDict(title="get_groups()")

    size: int | None = 100
    page: int | None = 1


class GetGroupsOutput(VcspResponse):
    """Output class for the get groups endpoint.

    Attributes:
        items: The items of the groups
        total: The total number of groups
        page: The page number
        size: The size of the groups
        pages: The total number of pages

    """

    items: list[CreateGroupOutput]
    total: int
    page: int
    size: int
    pages: int


class GetGroupInput(GroupInput):
    """Input class for the get a specific group endpoint."""

    model_config = ConfigDict(title="get_group()")


class GetGroupOutput(CreateGroupOutput):
    """Output class for the get a specific group endpoint.

    Attributes:
        size: The size of the group
        created_at: The created_at date
        updated_at: The updated_at date
        credential_configuration_urn: The credential configuration urn
        name: The name of the group
        description: The description of the group
        expired_at: The expired_at date

    """


class DeleteGroupInput(GroupInput):
    """Input class for the delete group endpoint.

    Attributes:
        name: The name of the group

    """

    model_config = ConfigDict(title="delete_group()")

    name: str


class GetGroupMembersInput(GroupInput):
    """Input class for the get group members endpoint."""

    model_config = ConfigDict(title="get_group_members()")


class GroupMember(BaseModel):
    """Base class for the group member.

    Attributes:
        subject_id: The subject_id of the group member
        credential_id: The credential_id of the group member
        expired_in_group: The expired_in_group of the group member
        claims: The claims of the group member
        tags: The tags of the group member

    """

    subject_id: str
    credential_id: str
    expired_in_group: str
    claims: dict
    tags: list[str]


class GetGroupMembersOutput(VcspResponse):
    """Output class for the get group members endpoint.

    Attributes:
        items: The items of the group members
        total: The total number of group members
        page: The page number
        size: The size of the group members
        pages: The total number of pages

    """

    items: list[GroupMember]
    total: int
    page: int
    size: int
    pages: int


class ListedCredential(GetCredentialOutput):
    """A credential as it appears in the system-wide credential listing.

    Attributes:
        subject_id: The account the credential belongs to

    """

    subject_id: str


class ListCredentialsInput(BaseModel):
    """Input class for the system-wide credential listing.

    Every field is a filter, and all of them are optional. Listing without one walks the
    whole system, which on a busy deployment is a lot of pages.

    Attributes:
        credential_configuration_urn: Only credentials created with this configuration
        tags: Only credentials carrying these tags
        page: The page to retrieve, starting at 1
        size: How many credentials per page

    """

    model_config = ConfigDict(title="list_credentials()")

    credential_configuration_urn: str | None = None
    tags: list[str] | None = None
    page: int | None = None
    size: int | None = None


class ListCredentialsOutput(VcspResponse):
    """Output class for the system-wide credential listing.

    Attributes:
        items: The credentials on this page
        total: The number of credentials matching the filters
        page: The page returned
        size: The page size
        pages: The number of pages

    """

    items: list[ListedCredential]
    total: int
    page: int
    size: int
    pages: int


class DeleteCredentialsInput(BaseModel):
    """Input class for bulk credential deletion.

    A group is the only filter the service accepts, and the operation is irreversible.
    Credentials in the group are deleted and removed from any other group they belong to.

    Attributes:
        group_name: The group whose credentials are deleted
        delete_empty_accounts: Whether to delete an account left with no credentials

    """

    model_config = ConfigDict(title="delete_credentials()")

    group_name: str
    delete_empty_accounts: bool = False


class GetCredentialSampleInput(SubjectInput, CredentialInput):
    """Input class for retrieving the sample behind a credential.

    Attributes:
        subject_id: The subject the credential belongs to
        credential_id: The credential whose sample to retrieve

    """

    model_config = ConfigDict(title="get_credential_sample()")


class GetCredentialSampleOutput(VcspResponse):
    """Output class for retrieving the sample behind a credential.

    The service answers with the raw bytes it was enrolled with, not with JSON.

    Attributes:
        content: The sample itself
        content_type: Its media type, such as `audio/wav` or `image/jpeg`

    """

    content: bytes
    content_type: str


class CredentialConfigurationInput(BaseModel):
    """Input class for retrieving one credential configuration.

    Attributes:
        urn: The urn of the credential configuration

    """

    model_config = ConfigDict(title="get_credential_configuration()")

    urn: str


class CredentialConfigurationOutput(VcspResponse):
    """Output class for retrieving one credential configuration.

    Attributes:
        urn: The urn of the credential configuration
        claims_schema: The JSON schema the `claims` of an enrolment must satisfy

    """

    urn: str
    claims_schema: dict


class TaskStatus(StrEnum):
    """The states an asynchronous task moves through.

    `TaskOutput.status` is a plain string rather than this enum, so a state the service adds
    later does not break deserialisation. Compare against these members.
    """

    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class TaskInput(BaseModel):
    """Input class for the task endpoints.

    Attributes:
        task_id: The identifier the service returned when the task was created

    """

    model_config = ConfigDict(title="get_task_result()")

    task_id: str


class TaskOutput(VcspResponse):
    """Output class describing one asynchronous task.

    Attributes:
        task_id: The identifier of the task
        status: One of the `TaskStatus` values
        progress: How far along the task is, from 0 to 100
        created_at: When the task was accepted
        started_at: When the task started, if it has
        finished_at: When the task finished, if it has
        expired_at: When the service will drop the task and its result

    """

    task_id: str
    status: str
    progress: float
    created_at: str | None = None
    started_at: str | None = None
    finished_at: str | None = None
    expired_at: str | None = None

    @property
    def is_finished(self) -> bool:
        """Whether the task has stopped running, successfully or not."""
        return self.status in (TaskStatus.COMPLETED, TaskStatus.FAILED)

    @property
    def succeeded(self) -> bool:
        """Whether the task finished successfully."""
        return self.status == TaskStatus.COMPLETED


class GetTasksOutput(VcspResponse):
    """Output class for the task listing.

    Attributes:
        items: The tasks on this page
        total: The number of active tasks
        page: The page returned
        size: The page size
        pages: The number of pages

    """

    items: list[TaskOutput]
    total: int
    page: int
    size: int
    pages: int


class GetTaskResultOutput(VcspResponse):
    """Output class for the outcome of a finished task.

    The shape depends on what created the task — a batch enrolment, a matching or a
    clustering all answer differently — so it is handed back as-is rather than forced into
    one model.

    Attributes:
        result: The outcome, as the service returned it

    """

    result: dict


class BatchApplicant(BaseModel):
    """One enrolment inside a batch.

    Attributes:
        sample: The biometric sample, as a path or as bytes
        applicant: The applicant to enrol, exactly as for a single enrolment
        filename: The name the sample takes inside the archive. Derived from the path, or
            generated for bytes, when omitted. It only has to be unique within the batch

    """

    sample: Media
    applicant: Applicant
    filename: str | None = None

    model_config = ConfigDict(arbitrary_types_allowed=True)


class BatchEnrollmentInput(BaseModel):
    """Input class for batch enrolment.

    The service takes a TAR archive holding the samples and an `applicants.json` that points
    at them. Pass `applicants` and the client builds it; pass `batch_file` if you have one
    already, which avoids holding a large batch in memory twice.

    Attributes:
        applicants: The enrolments to perform
        batch_file: A prepared TAR archive, as a path or as bytes

    """

    applicants: list[BatchApplicant] | None = None
    batch_file: str | bytes | None = None

    model_config = ConfigDict(arbitrary_types_allowed=True, title="enroll_batch()")

    @field_validator("batch_file")
    def exactly_one_source(cls, value: object, info: object):
        if value is None and not info.data.get("applicants"):
            error = "provide either applicants or batch_file"
            raise ValueError(error)
        if value is not None and info.data.get("applicants"):
            error = "provide applicants or batch_file, not both"
            raise ValueError(error)
        return value


class TaskCreatedOutput(VcspResponse):
    """Output class for any operation the service accepts and runs asynchronously.

    Batch enrolment, clustering, and a large group population all answer this way. Follow the
    work with `get_task` or `wait_for_task`, and collect it with `get_task_result`.

    Attributes:
        task_id: The task the work runs under
        created_at: When the task was accepted

    """

    task_id: str
    created_at: str


# The name batch enrolment used before other endpoints started answering the same way.
BatchEnrollmentOutput = TaskCreatedOutput


class SubjectClaimant(BaseModel):
    """The reference for a 1:1 matching: one subject's credential.

    Attributes:
        subject_id: The subject to match against
        credential_configuration_urn: Which of the subject's credentials to use
        assurance_method_urn: The assurance method to apply
        assurance: The values that method requires, such as `{"biometric_threshold": 0.5}`

    """

    subject_id: str
    credential_configuration_urn: str
    assurance_method_urn: str
    assurance: dict


class GroupClaimant(BaseModel):
    """The reference for a 1:N matching: every credential in a group.

    Attributes:
        group_name: The group to match against
        assurance_method_urn: The assurance method to apply
        assurance: The values that method requires
        limit: How many results to return, best first
        filter: A JsonLogic expression narrowing the group, such as
            `{"AND": [{"tag": "role:employee"}]}`

    """

    group_name: str
    assurance_method_urn: str
    assurance: dict
    limit: int | None = None
    filter: dict | None = None


class MatchingInput(BaseModel):
    """Input class for a matching operation.

    Attributes:
        sample: The biometric sample to match, as a path or as bytes
        claimant: What to match it against — a `SubjectClaimant` for 1:1, a `GroupClaimant`
            for 1:N
        sample_processing: Options for reading the sample, such as `{"nchannel": 1}`
        content_type: The media type to declare for the sample. Inferred when omitted

    """

    sample: Media
    claimant: SubjectClaimant | GroupClaimant
    sample_processing: dict | None = None
    content_type: str | None = None

    model_config = ConfigDict(arbitrary_types_allowed=True, title="match()")


class MatchingResult(BaseModel):
    """One candidate a matching operation scored.

    Attributes:
        subject_id: The subject the matched credential belongs to
        biometrics_score: How closely the sample matched, from 0 to 1
        match_status: `HIT` or `MISS`, against the assurance thresholds

    """

    subject_id: str
    biometrics_score: float
    match_status: str


class MatchedSample(BaseModel):
    """What the service made of the sample it was given.

    Attributes:
        type: `voice` or `face`
        content_type: The media type it was read as
        analysis: Quality figures, such as net speech duration or an authenticity score
        sample_processing: The processing options that were applied

    """

    type: str
    content_type: str
    analysis: dict
    sample_processing: dict | None = None


class MatchingOutput(VcspResponse):
    """Output class for a matching operation.

    Attributes:
        results: The candidates, best first
        nhits: How many of them are a `HIT`
        sample: What the service made of the sample

    """

    results: list[MatchingResult]
    nhits: int
    sample: MatchedSample


class GroupAction(StrEnum):
    """The actions `modify_group` can perform."""

    POPULATE = "populate"
    REMOVE = "remove"
    UPDATE_INFO = "update_info"


class GroupMembershipSource(BaseModel):
    """Which credentials a populate or remove applies to.

    At least one of the two is required.

    Attributes:
        subjects: Subject ids whose credentials to add or remove
        tags: Tags whose credentials to add or remove

    """

    subjects: list[str] | None = None
    tags: list[str] | None = None


class ModifyGroupInput(GroupInput):
    """Input class for modifying a group.

    Attributes:
        name: The group to modify
        action: `populate`, `remove` or `update_info`
        from_: Which credentials to add or remove. Required for populate and remove, and
            serialised as `from`, which is a reserved word in Python
        credential_ttl: How long added credentials stay in the group, as an ISO 8601
            duration such as `P30D`
        description: A new description, for `update_info`
        expired_at: A new retention period, for `update_info`, as an ISO 8601 duration

    """

    action: str
    from_: GroupMembershipSource | None = Field(default=None, alias="from")
    credential_ttl: str | None = None
    description: str | None = None
    expired_at: str | None = None

    model_config = ConfigDict(populate_by_name=True, title="modify_group()")


class CredentialTagAction(StrEnum):
    """The actions `modify_credential_tags` can perform."""

    ADD = "add"
    REMOVE = "remove"


class ModifyCredentialTagsInput(SubjectInput, CredentialInput):
    """Input class for changing the tags on a credential.

    Attributes:
        subject_id: The subject the credential belongs to
        credential_id: The credential to change
        action: `add` or `remove`
        tags: The tags to add or remove. They must already exist in the system

    """

    model_config = ConfigDict(title="modify_credential_tags()")

    action: str
    tags: list[str]


class ClusteringInput(GroupInput):
    """Input class for starting a clustering task on a group.

    Clustering is only supported for groups of face credentials; a voice group is rejected
    with `ClusteringNotSupportedError`.

    Attributes:
        name: The group to cluster
        assurance_method_urn: The clustering assurance method to apply
        properties: The values that method requires, such as
            `{"similarity_threshold": 0.5, "mode": "similarity_based"}`. Note the service
            calls this `properties`, not `assurance` as everywhere else

    """

    model_config = ConfigDict(title="start_clustering()")

    assurance_method_urn: str
    properties: dict
